FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm install --save-dev @types/node

COPY . .

# Angular default dev port
EXPOSE 4200

# Note: The 'command' is handled by docker-compose.dev.yml
# to allow for easy adjustments without rebuilding the image.
